"""roles model

Revision ID: a7a368d7e452
Revises: e8219d64f19f
Create Date: 2022-10-20 09:49:51.672846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a368d7e452'
down_revision = 'e8219d64f19f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__role'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], name=op.f('fk__user_role__id_role__role')),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('fk__user_role__id_user__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_role'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
